### ISSUE TITLE
NullPointerException when passing empty chunk from body filter

### ISSUE THREAD

**Issue by novakg** [nginx-clojure/nginx-clojure#147]
I'm trying to completely replace the body of a proxied page using a body filter. The way in which I think it should be done is that the body filter returns empty chunk in every call where isLast = false, and it returns the new body when isLast is true.

My nginx.conf looks like:

    location / {
        body_filter_type 'java';
        body_filter_name 'org.mypackage.MyClass';        
        proxy_set_header Accept-Encoding deflate;
        proxy_pass http://www.myproxiedpage.com/;
    }

(Accept-Encoding deflate; has been added to avoid receiving gzipped content for the moment...)

MyClass does the following:

    public class MyClass implements NginxJavaBodyFilter {
    
        @Override
        public Object[] doFilter(Map<String, Object> request, InputStream bodyChunk, boolean isLast) throws IOException {
        ...
            if (!isLast) {
                return new Object[] {null, null, ""};
            }
            return new Object[] {200, null, "<html><body>This is the new body of the request</body></html>"};
        }
    }

I get the following exception:

    2016-12-02 08:26:39[error][28][main]server unhandled exception!
    java.lang.NullPointerException
            at nginx.clojure.NginxChainWrappedInputStream.close(NginxChainWrappedInputStream.java:217)
            at nginx.clojure.java.NginxJavaHandler.process(NginxJavaHandler.java:120)
            at nginx.clojure.NginxSimpleHandler.handleRequest(NginxSimpleHandler.java:166)
            at nginx.clojure.NginxSimpleHandler.execute(NginxSimpleHandler.java:97)
            at nginx.clojure.NginxClojureRT.eval(NginxClojureRT.java:1125)

I'm using the version 0.4.4

Another question: is there a planned release date for 0.4.5?

**Comment by xfeep** [comment]
It has been fixed in the master branch. Please try it.
0.4.5 will be released at the end of this month if I have time.

**Comment by novakg** [comment]
Now I'm testing with the master branch and I can still see:

    2016-12-05 08:33:29[error][14608][main]server unhandled exception!
        java.lang.NullPointerException
            at nginx.clojure.java.NginxJavaHandler.process(NginxJavaHandler.java:120)
            at nginx.clojure.NginxSimpleHandler.handleRequest(NginxSimpleHandler.java:166)
            at nginx.clojure.NginxSimpleHandler.execute(NginxSimpleHandler.java:97)
            at nginx.clojure.NginxClojureRT.eval(NginxClojureRT.java:1125)

**Comment by xfeep** [comment]
@novakg Did you rebuild the jar file about nginx-clojure?

**Comment by novakg** [comment]
Yes, I cloned the master branch from github, did a `lein jar` and copied the `nginx-clojure/target/nginx-clojure-0.4.4.jar` file under my NGinx instance (replaced the jar there) and restarted NGinx.
What commit in the master branch do you think should fix this issue? I would check if my local copy is correct and has those changes.

**Comment by xfeep** [comment]
@novakg Was your executable binary  file , say nginx, still replaced by rebuild with the master branch of nginx-clojure?

**Comment by knasim** [comment]
which is the best version of nginx supported by this module.   i'm using 1.11.6 and when the java handler directive is called - the control never passed to my proxy_pass in my nginx location block.  instead i get any "emtpy reply from server" from curl.  i'm using module version 0.4.4

**Comment by novakg** [comment]
It seems to be solved in the main branch indeed. Thanks for the help.

**Comment by knasim** [comment]
actually it depends on which java content handler you are using .   there are 2 of them in fact. 
if you use the Content_Rewrite then the control is never handed back to continue processing. 
If you use the Rewrite_Handler - then the control is passed back to your location block and your proxy_pass is executed.  You have to read the documentation and look at the unit tests in the project.
